tap "hashicorp/tap"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
brew "allure"
brew "htop"
brew "zookeeper", restart_service: true
brew "kafka", restart_service: true
brew "kcat"
brew "openssl@3"
brew "poetry"
brew "postgresql", restart_service: true
brew "pyenv"
brew "redis", restart_service: true
brew "hashicorp/tap/terraform"
cask "1password"
cask "alacritty"
cask "cloudflare-warp"
cask "docker"
cask "google-chrome"
cask "karabiner-elements"
cask "krisp"
cask "paw"
cask "postico"
cask "postman"
cask "privatevpn"
cask "pycharm"
cask "slack"
cask "spotify"
cask "sublime-merge"
cask "sublime-text"
cask "teamviewer"
cask "vanilla"
cask "whatsapp"
cask "zoom"
